export const collaborationsData = [
  { year: "2025", items: ["Mr Phormula - Cymraeg Worldwide (Galles)", "JK - Astra Aeterna (Italy)", "Hanzo Reiza - Hikki Dojo Freestyle 14"] },
  { year: "2024", items: ["JK - Supernovae (Italy)", "Mastafive - Euforia Collabo (Italy)", "Mastafive & Fabio Musta - La prima volta con Oyoshe & Kenzie"] },
  { year: "2023", items: ["Simmy Summer - Chaos (Italy)", "Zell Dj - Serious (Italy)"] },
  { year: "2022", items: ["Stritti - Strittmatazz (Italy)"] },
  { year: "2021", items: ["Aa.vv. Summer Vibes vol.2 - B.M. records", "Stritti - Fantasy (Italy)"] },
  { year: "2020", items: ["Strike The Head x Lilym - Il cielo in una stanza Rmx", "Aa.vv. Summer Vibes vol.1 - B.M. records", "Al Fo - I Believe (Italy)", "Unitidalgroove - Re senza Trono", "Viola Ent. - Torino non e piu Fiat (Italy)", "Stritti - RiRappresento (Italy)"] },
  { year: "2017", items: ["Josef K - No Matter (Romania)", "Rand Slam - Rimajinasi (Indonesia)", "Keep it Real - Fallo Realmente vol.1 (Italy)"] },
  { year: "2016", items: ["eMCeeM - International Hip Hop (Poland)", "Mr Phormula - LLWYBRAU (Wales)", "Pat - RapDiecicento (Italy)", "Lil bac - L invisibile (Italy)", "Sparadust - Boom Balcanic Bap (Italy)", "Stritti - HipHopCorn (Italy)"] },
  { year: "2015", items: ["San E - The Boy Who Cried Wolf (South Korea)", "Hip Hop for The World - HipHopisHipHop"] },
  { year: "2014", items: ["Aa.vv. The Movement Mixtape vol.1", "Dj Seby - Blackzone Mixtape vol.6", "Radio Rade & Dj Spark - Il Progetto Brunovic", "Manifesto - Seriamente 12 inch"] },
  { year: "2013", items: ["Jap & Paggio - HipHopcrisia B.M. records", "Bustaphort - Collection 2006-2012 (Spain)", "Dj Jad - Cool Tape Mixtape", "G-Soul - Tridream State (Spain)", "DragWan - Lost Traxxx Vinile", "Rikom Carnera - Il suono della campana"] },
  { year: "2012", items: ["Rico - HERTZMUSIC", "Erma - KUMI", "Aa.vv. 4MYPEOPLE vol.1 WeGotFlava"] },
  { year: "2011", items: ["Kabin - CHECKPOINT (Hungary)", "7Peccati - DYNAMIKE 2007", "DragWan - Colpiscimi ep", "Aa.vv. Save HipHop compilation", "Elfa - Missantropa", "Kitz - Music Paiura", "Erma - Regnum Sardiniae", "El Cebero de la SL - Fina Estampa (Colombia)", "Bolo Creatore - Golem 2"] },
  { year: "2010", items: ["Ruido & Fame126 - Zero Cloni Mixtape vol.1", "El Cebero de la SL - Tiempo pa Matar (Colombia)"] },
  { year: "2009", items: ["Aa.vv. TrainingDay vol.1 Groove Magazine", "Maury B - One Day", "Mecom - La classe delle elementari", "BabyTraxx - Babytraxx is James Digger (France)", "SupaBeatz prod. - 2 Calci in bocca"] },
  { year: "2008", items: ["Don Stefano - Diamanti Mixtape"] },
  { year: "2007", items: ["Aa.vv. Xmas Compilation vol.2", "Don Stefanuccio - Dolce Veleno Mixtapes"] },
  { year: "2006", items: ["Bolo Creatore - Golem", "KjNoone - Brotha Fight", "21 Grammi - Orgoglio nazionale", "Erma - Ermatico", "Mas.T - Rap Games", "Dhiram Records - Street Tape vol.1", "Dj Frankie O - Insoliti Inediti"] },
  { year: "2005", items: ["Lingo - S.T.A.W.A. (Poland)", "Cisa - Suonoibrido vol.2", "Kalafro Sound Power - Bergamotto Showcase", "Aa.vv. Music & Movie compilation SkyTv", "Mastafive - Dammi un beat"] },
  { year: "2004", items: ["Aa.vv. Sampler03 DaBombMagazine", "Cisa - Suonoibrido vol.1", "Aa.vv Hip Hop United (Nederland)", "Adry - Va Cosi (Spain)", "Quality Bastard - Basement 2000-2004", "Canebullo - Solista ma non troppo", "Izanami - Con le unghie"] },
  { year: "2003", items: ["Dj Mesta - Invasione Mixtape vol.1", "Hiphop&Stop - Underground", "Dabee & Black King - Nucleo Compatto vol.2", "Misterkumasca - Impronte"] },
  { year: "2002", items: ["Erma - Ermageddon", "Quality Bastard - Cap Tost Mixtape", "Mikron - HipHop Next Stop", "Soprasotto prod. - SoprasottoClick", "Dabee - Nucleo Compatto"] },
  { year: "2001", items: ["Supervirzi Corporation - Zona Stretta"] }
];
